version: '3'

services:
  api:
    build: gift-tracker-backend
    depends_on:
      - db
    ports:
      - "8081:8080"
  db:
    image: postgres:latest
    environment:
      - DATABASE_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5433:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data