/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {

  // Deletes ALL existing entries
  await knex.raw('TRUNCATE TABLE birthday RESTART IDENTITY CASCADE')
  await knex('birthday').insert([
    { name: 'Averys Housewarming', birthdate: '2024-10-14', interests: 'Fitness', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 6, wishlist_id: 1 },
    { name: 'Jamiel Trimble', birthdate: '2024-06-25', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 1, wishlist_id: 1 },
    { name: 'Stephen Milburn', birthdate: '2024-06-28', interests: 'Coding', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 2, wishlist_id: 1 },
    { name: 'Nikki Khurshed', birthdate: '2024-09-25', interests: 'Cyber', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 4, wishlist_id: 1 },
    { name: 'G. Noel', birthdate: '2024-11-25', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 5, wishlist_id: 1 },
    { name: 'Will Dallmanns Promotion Party', birthdate: '2024-09-01', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 3, wishlist_id: 1 },
    { name: 'George Washington', birthdate: '1732-02-22', interests: 'Outdoors', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 6, wishlist_id: 1 },
    { name: 'Thomas Jefferson', birthdate: '1953-04-07', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 1, wishlist_id: 1 },
    { name: 'John Adams', birthdate: '1999-05-02', interests: 'Cooking', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 2, wishlist_id: 1 },
    { name: 'Benjamin Franklin', birthdate: '1777-07-13', interests: 'Cooking', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 4, wishlist_id: 1 },
    { name: 'Alexander Hamilton', birthdate: '2024-11-25', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 5, wishlist_id: 1 },
    { name: 'John Jay', birthdate: '2000-09-22', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 3, wishlist_id: 1 },
    { name: 'James Madison', birthdate: '2017-01-14', interests: 'Fitness', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 6, wishlist_id: 1 },
    { name: 'Robert De Niro', birthdate: '2024-06-22', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 1, wishlist_id: 1 },
    { name: 'Leonardo DiCaprio', birthdate: '2024-06-23', interests: 'Jewelry', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 2, wishlist_id: 1 },
    { name: 'Marilyn Monroe', birthdate: '1847-09-20', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 4, wishlist_id: 1 },
    { name: 'Morgan Freeman', birthdate: '1923-11-29', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 5, wishlist_id: 1 },
    { name: 'Johnny Depp', birthdate: '2010-09-01', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 3, wishlist_id: 1 },
    { name: 'Charles Chaplin', birthdate: '1627-10-12', interests: 'Fitness', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 6, wishlist_id: 1 },
    { name: 'Al Pacino', birthdate: '1977-06-27', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 1, wishlist_id: 1 },
    { name: 'Bruce Lee', birthdate: '1378-06-28', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 2, wishlist_id: 1 },
    { name: 'Angelina Jolie', birthdate: '1890-09-20', interests: 'Jewelry', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 4, wishlist_id: 1 },
    { name: 'Anthony Hopkins', birthdate: '1787-11-25', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 5, wishlist_id: 1 },
    { name: 'Natalie Portman', birthdate: '1342-09-01', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 3, wishlist_id: 1 },
    { name: 'Sandra Bullock', birthdate: '1984-10-14', interests: 'Fitness', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 6, wishlist_id: 1 },
    { name: 'Tom Cruise', birthdate: '1872-06-12', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 1, wishlist_id: 1 },
    { name: 'Heath Ledger', birthdate: '1729-06-28', interests: 'Outdoors', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 2, wishlist_id: 1 },
    { name: 'Antonio Banderas', birthdate: '1842-09-25', interests: 'Outdoors', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 4, wishlist_id: 1 },
    { name: 'Nicole Kidman', birthdate: '1788-11-25', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 5, wishlist_id: 1 },
    { name: 'Robin Williams', birthdate: '1999-09-01', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 3, wishlist_id: 1 },
    { name: 'George Clooney', birthdate: '1846-10-14', interests: 'Fitness', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 6, wishlist_id: 1 },
    { name: 'Bruce Willis', birthdate: '1344-06-17', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 1, wishlist_id: 1 },
    { name: 'Russell Crowe', birthdate: '1989-06-28', interests: 'Jewelry', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 2, wishlist_id: 1 },
    { name: 'Nicolas Cage', birthdate: '1869-09-26', interests: 'Outdoors', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 4, wishlist_id: 1 },
    { name: 'Brad Pitt', birthdate: '1555-09-01', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 3, wishlist_id: 1 },
    { name: 'Clint Eastwood', birthdate: '1851-10-14', interests: 'Fitness', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 6, wishlist_id: 1 },
    { name: 'Demi Moore', birthdate: '1333-06-11', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 1, wishlist_id: 1 },
    { name: 'Mel Gibson', birthdate: '1969-06-28', interests: 'Outdoors', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 2, wishlist_id: 1 },
    { name: 'Jim Carrey', birthdate: '1827-09-07', interests: 'Jewelry', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 4, wishlist_id: 1 },
    { name: 'Mark Wahlberg', birthdate: '1344-11-25', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 5, wishlist_id: 1 },
    { name: 'Arnold Schwarzenegger', birthdate: '1882-09-01', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 3, wishlist_id: 1 },
    { name: 'Sylvester Stallone', birthdate: '1941-10-14', interests: 'Fitness', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 6, wishlist_id: 1 },
    { name: 'Colin Farrell', birthdate: '1949-06-25', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 1, wishlist_id: 1 },
    { name: 'Bradley Cooper', birthdate: '1952-06-28', interests: 'Jewelry', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 2, wishlist_id: 1 },
    { name: 'Liam Neeson', birthdate: '1926-09-16', interests: 'Jewelry', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 4, wishlist_id: 1 },
    { name: 'Matt Damon', birthdate: '1722-11-29', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 5, wishlist_id: 1 },
    { name: 'Fyodor Dostoevsky', birthdate: '1823-09-01', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 3, wishlist_id: 1 },
    { name: 'Mark Twain', birthdate: '1823-10-14', interests: 'Fitness', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 6, wishlist_id: 1 },
    { name: 'Leo Tolstoy ', birthdate: '1898-06-18', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 1, wishlist_id: 1 },
    { name: 'George Orwell', birthdate: '1955-06-28', interests: 'Outdoors', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 2, wishlist_id: 1 },
    { name: 'Aldous Huxley ', birthdate: '1221-09-25', interests: 'Jewelry', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 4, wishlist_id: 1 },
    { name: 'Arthur Conan Doil', birthdate: '1896-11-01', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 5, wishlist_id: 1 },
    { name: 'Miguel de Cervantes Saavedra', birthdate: '1972-09-01', interests: 'Sports', relationship: 'family', priority: 1, gift_ideas: 'gift ideas here', notes: 'notes entered here', user_id: 3, wishlist_id: 1 },
  ]);
};